### ISSUE TITLE
http://ot.substance.io/demo/ is down

### ISSUE THREAD

**Issue by antonkulaga** [Operational-Transformation/ot.js#25]
I am trying to open http://ot.substance.io/demo/ but it freezes

**Comment by kishorenc** [comment]
I'm not able to access the new implementation - link is down.

**Comment by jankeromnes** [comment]
I confirm http://ot-demo.timbaumann.info is down, but the heroku link still works: http://operational-transformation.herokuapp.com

**Comment by timjb** [comment]
Seems to work here.

**Comment by jankeromnes** [comment]
Looks like a DNS lookup fail on my side, but http://timbaumann.info/ works.

**Comment by timjb** [comment]
I've recently noticed some DNS lookup flakiness on my domain as well. I'm using Digital Ocean's DNS servers for [ot-demo.timbaumann.info](http://ot-demo.timbaumann.info). Last time the demo was down, resetting the DNS routing on Digital Ocean helped.
