### ISSUE TITLE
Out of sync when deleting on same cursor position on several clients

### ISSUE THREAD

**Issue by jachzen** [Operational-Transformation/ot.js#30]
I found a bug which leads to unsynchronized state. To reproduce do the following:
I could reproduce it with my own service but also with ot-demo.timbaumann.info.

Open same document on several clients, now remove on both sides one or more characters.
Afterwards the document is out of sync.

**Comment by satyanarayanaAmzur** [comment]
hi friends if  any one willing to help me with similar problem please check this issue
https://github.com/aullman/opentok-editor/issues/6
